export const GET_AREAS_BY_IDS = 'GET_AREAS_BY_IDS'
export const GET_AREAS_BY_IDS_SUCCESS = 'GET_AREAS_BY_IDS_SUCCESS'
export const GET_AREAS_BY_IDS_FAIL = 'GET_AREAS_BY_IDS_FAIL'

export const CACHING_AREAS = 'CACHING_AREAS'