export const SET_SDK_READY = 'SET_SDK_READY'
export const SET_LOGIN_STATUS ='SET_LOGIN_STATUS'

export const UNSHIFT_MESSAGE_LIST = 'UNSHIFT_MESSAGE_LIST'
export const UPDATE_ALL_CONVERSATION = 'UPDATE_ALL_CONVERSATION'
export const UPDATE_CURRENT_MESSAGE_LIST = 'UPDATE_CURRENT_MESSAGE_LIST'
export const UPDATE_CURRENT_CONVERSATION = 'UPDATE_CURRENT_CONVERSATION'
export const UPDATE_NEXT_REQ_MESSAGE_ID = 'UPDATE_NEXT_REQ_MESSAGE_ID'

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const RESET_CURRENT_CONVERSATION = 'RESET_CURRENT_CONVERSATION'
export const RESET_ALL_CONVERSATION = 'RESET_ALL_CONVERSATION'
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE'
export const CHANGE_MESSAGE_STATUS = 'CHANGE_MESSAGE_STATUS'

export const UPDATE_SELLER_IM_INFO = 'UPDATE_SELLER_IM_INFO'
export const SET_BLACKLIST = 'SET_BLACKLIST'
export const UPDATE_BLACKLIST = 'UPDATE_BLACKLIST'

export const UPDATE_GROUP_LIST = 'UPDATE_GROUP_LIST'
export const RESET_GROUP = 'RESET_GROUP'

export const RESET_IM = 'RESET_IM'

export const CHECKOUT_CONVERSATION = 'CHECKOUT_CONVERSATION'

export const UPDATE_IS_COMPLETED = 'UPDATE_IS_COMPLETED'
export const CHANGE_IS_LOADING = 'CHANGE_IS_LOADING'
