export const GET_SELLER_WORKSPACE = 'GET_SELLER_WORKSPACE'
export const GET_SELLER_WORKSPACE_SUCCESS = 'GET_SELLER_WORKSPACE_SUCCESS'
export const GET_SELLER_WORKSPACE_FAIL = 'GET_SELLER_WORKSPACE_FAIL'
export const UPDATE_REDUX_WORKSPACE_STATUS_TO_BLANK = 'UPDATE_REDUX_WORKSPACE_STATUS_TO_BLANK'