export const GET_SELLER = 'GET_SELLER'
export const FETCH_REQUEST_SELLER_INFO ='FETCH_REQUEST_SELLER_INFO'


export const FETCH_SELLER_AUTH = 'FETCH_SELLER_AUTH'
export const FETCH_SELLER_AUTH_SUCCESS = 'FETCH_SELLER_AUTH_SUCCESS'
export const FETCH_SELLER_AUTH_FAIL = 'FETCH_SELLER_AUTH_FAIL'

export const UPDATE_SLLER = 'UPDATE_SLLER'
export const UPDATE_SLLER_SUCCESS = 'UPDATE_SLLER_SUCCESS'
export const UPDATE_SLLER_FAIL = 'UPDATE_SLLER_FAIL'

export const SELLER_LOGOUT = 'SELLER_LOGOUT'