export const GET_SELLER_STATISTICS = 'GET_SELLER_STATISTICS'
export const GET_SELLER_STATISTICS_SUCCESS = 'GET_SELLER_STATISTICS_SUCCESS'
export const GET_SELLER_STATISTICS_FAIL = 'GET_SELLER_STATISTICS_FAIL'

export const GET_SELLER_DYNAMIC_RECORDS = 'GET_SELLER_DYNAMIC_RECORDS'
export const GET_SELLER_DYNAMIC_RECORDS_SUCCESS = 'GET_SELLER_DYNAMIC_RECORDS_SUCCESS'
export const GET_SELLER_DYNAMIC_RECORDS_FAIL = 'GET_SELLER_DYNAMIC_RECORDS_FAIL'

export const GET_SELLER_REPORT_OVERVIEW = 'GET_SELLER_REPORT_OVERVIEW'
export const GET_SELLER_REPORT_OVERVIEW_SUCCESS = 'GET_SELLER_REPORT_OVERVIEW_SUCCESS'
export const GET_SELLER_REPORT_OVERVIEW_FAIL = 'GET_SELLER_REPORT_OVERVIEW_FAIL'

export const GET_GUEST_RANKING = 'GET_GUEST_RANKING'
export const GET_GUEST_RANKING_SUCCESS = 'GET_GUEST_RANKING_SUCCESS'
export const SET_GUEST_RANKING_PROJECT_ID = 'SET_GUEST_RANKING_PROJECT_ID'
export const GET_GUEST_RANKING_FAIL = 'GET_GUEST_RANKING_FAIL'
export const GET_GUEST_RANKING_FINALLY = 'GET_GUEST_RANKING_FINALLY'
export const GET_GUEST_RANKING_START = 'GET_GUEST_RANKING_START'
export const SET_TIME_TYPE = 'SET_TIME_TYPE'
