// 设置默认的激励方案/会籍
export const GET_DEFAULT_INCENTIVE_PLAN = 'GET_DEFAULT_INCENTIVE_PLAN'
export const GET_DEFAULT_INCENTIVE_PLAN_SUCCESS = 'GET_DEFAULT_INCENTIVE_PLAN_SUCCESS'
export const GET_DEFAULT_INCENTIVE_PLAN_FAIL = 'GET_DEFAULT_INCENTIVE_PLAN_FAIL'
export const SET_DEFAULT_INCENTIVE_PLAN = 'SET_DEFAULT_INCENTIVE_PLAN'
